In [1]:
import numpy as np

In [5]:
grades = np.array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

In [7]:
# mean
print(np.mean(grades))

87.5


In [9]:
# meadian
print(np.median(grades))

88.5


In [11]:
# standard deviation
print(np.std(grades))

6.591661399070799


In [13]:
print(grades.std())

6.591661399070799


In [15]:
# min
print(np.min(grades))

75


In [17]:
# Max
print(np.max(grades))

98


In [19]:
#How to sort
grades.sort()
print(grades)

[75 80 83 85 88 89 90 92 95 98]


In [27]:
# numpy aggregate Max
print(grades[9])

98


In [31]:
print(grades.argmax())

9


In [33]:
# numpy aggreagte min
print(grades.argmin())

0


In [35]:
print(grades[0])

75


In [47]:
# Finding students that score above 90
greater_than_90 = np.where(grades > 90)

print(np.count_nonzero(greater_than_90))

3


In [53]:
print(np.mean(grades>90)*100)

30.0


In [55]:
# Finding students that score above 75
greater_than_75 = np.where(grades > 75)

print(np.count_nonzero(greater_than_75))

9


In [57]:
print(np.mean(grades>75)*100)

90.0


In [59]:
high_perfomers = grades[grades > 90]
print(high_perfomers)

[92 95 98]


In [61]:
passing_grades = grades[grades > 75]
print(passing_grades)

[80 83 85 88 89 90 92 95 98]
